site_name: tzxtools
site_author: Richard KÃ¶rber
site_url: https://shredzone.org/docs/tzxtools/index.html
theme:
    name: material
    font: false
    icon:
        logo: 'fontawesome/solid/save'
    palette:
        primary: 'blue'
        accent: 'deep orange'
nav:
  - 'Installation': 'index.md'
  - 'tzxcat': 'tzxcat.md'
  - 'tzxcleanup': 'tzxcleanup.md'
  - 'tzxcut': 'tzxcut.md'
  - 'tzxls': 'tzxls.md'
  - 'tzxmerge': 'tzxmerge.md'
  - 'tzxsplit': 'tzxsplit.md'
  - 'tzxtap': 'tzxtap.md'
  - 'tzxwav': 'tzxwav.md'
